# permissions for end users to view remoteinstallations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: remoteinstallation-viewer-role
rules:
- apiGroups:
  - installs.remote-installer.io
  resources:
  - remoteinstallations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - installs.remote-installer.io
  resources:
  - remoteinstallations/status
  verbs:
  - get
